### ISSUE TITLE
请问 auth_chain_b 和 tls1.2 的兼容问题是在哪条 commit 修复的？

### ISSUE THREAD

**Issue by kuoruan** [shadowsocksrr/shadowsocksr-libev#4]
具体是哪个位置的问题？ 感谢

**Comment by Love4Taylor** [comment]
https://github.com/shadowsocksrr/shadowsocksr-libev/commit/800f5ade143189f277045091e687998c9e0a2c39

**Comment by Akkariiin** [comment]
https://github.com/shadowsocksrr/shadowsocksr-libev/commit/800f5ade143189f277045091e687998c9e0a2c39#diff-4330886bed073a4c041810dfa954c978L513

remove follow code and it will fix.

```
server->overhead = 4;
```

<hr/>

because begin follow line

https://github.com/shadowsocksrr/shadowsocksr-libev/blob/800f5ade143189f277045091e687998c9e0a2c39/src/local.c#L899

```
                    _server_info.overhead = (uint16_t)
                            (
                                    (server_env->protocol_plugin ?
                                     server_env->protocol_plugin->get_overhead(server->protocol) : 0)
                                    +
                                    (server_env->obfs_plugin ?
                                     server_env->obfs_plugin->get_overhead(server->obfs) : 0)
                            );
```

those code count the overhead for protocol_plugin those must sum all the overhead from obfs_plugin and protocol_plugin. 
The reason is that protocol_plugin is the last plugin in the processing line.

**Comment by kuoruan** [comment]
OK, Thx. I have extracted the code.
